// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"just-go/stage-3-architecture/12-clean-architecture/infrastructure/memory"
	"just-go/stage-3-architecture/12-clean-architecture/interface/httpapi"
	"just-go/stage-3-architecture/12-clean-architecture/usecase"
)

// Injectors from wire.go:

func initializeHandler() *httpapi.Handler {
	articleRepository := memory.NewArticleRepository()
	clock := usecase.NewSystemClock()
	idGenerator := usecase.NewSequentialIDGenerator()
	articleService := usecase.NewArticleService(articleRepository, clock, idGenerator)
	handler := httpapi.NewHandler(articleService)
	return handler
}
